CMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_url = "/app"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from autoslug import AutoSlugField

gender_choices = [
    ('M', 'Male'),
    ('F', 'Female')
]

# Create your models here.


class Company(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    description = HTMLField(blank=True, default=u'')
    promo_url = models.URLField(blank=True, null=True)
    address = models.TextField(max_length=500, blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=25, blank=True, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    key = AutoSlugField(populate_from='title', unique_with=['name', 'creation_date'])
    password = models.CharField(max_length=150, blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    company_logo = models.ImageField(default='', blank=True, null=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    designation = models.CharField(max_length=50, blank=True, null=True)
    descripsion = models.TextField(max_length=500, blank=True, null=True)
    gender = models.CharField(max_length=10, choices=gender_choices, default='None', null=True, blank=True)
    profile_pic = models.ImageField(default='', blank=True, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)


class AboutUs(models.Model):
    company = models.OneToOneField(Company, on_delete=models.CASCADE)
    title = models.CharField(max_length=250, null=True, blank=True)
    details = HTMLField(blank=True, default=u'')
    mission = HTMLField(blank=True, default=u'')
    vission = HTMLField(blank=True, default=u'')
    mosaic = HTMLField(blank=True, default=u'')
    image = models.ImageField(default='about_us.jpg', blank=True, null=True)


class Services(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    details = HTMLField(blank=True, default=u'')


class Blog(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    descripsion = HTMLField(blank=True, default=u'')
    creation_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='', blank=True, null=True)


class ClientReview(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    designation = models.CharField(max_length=50, blank=True, null=True)
    review = models.TextField(max_length=500)
    image = models.ImageField(default='', blank=True, null=True)


class AnimationView(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    header = models.CharField(max_length=50)
    title = models.CharField(max_length=300)
    descripsion = models.TextField(max_length=500, blank=True, null=True)
    backgroun_image = models.ImageField(default='', blank=True, null=True)


class InteriorDesignImage(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    image = models.ImageField(default='')

app/templates/web/about.html
{% extends 'web/web_base.html' %}
{% load static %}
{% block content %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'web/images/bg_1.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">About Us</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'web_index' company.key company.id %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About us <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section">
			<div class="container">
				<div class="row no-gutters">
					<div class="col-md-5 p-md-5 img img-2" style="background-image: url('/media/{{company.aboutus.image}}');">
					</div>
					<div class="col-md-7 wrap-about pb-md-5 ftco-animate">
	          <div class="heading-section mb-5 pl-md-5">
	          	<div class="pl-md-5 ml-md-5">
		          	<span class="subheading subheading-with-line"><small class="pr-2 bg-white">About</small></span>
		            <h2 class="mb-4">{{company.aboutus.title}}</h2>
	            </div>
	          </div>
	          <div class="pl-md-5 ml-md-5 mb-5">
                  <p>{{company.aboutus.details|safe}}</p>
							<p><a href="#" class="btn-custom">Learn More <span class="ion-ios-arrow-forward"></span></a></p>
						</div>
					</div>
				</div>
				<div class="row mt-5 pt-4">
					<div class="col-md-4 ftco-animate">
						<h3 class="h4">Mission</h3>
						<p>{{company.aboutus.mission| safe}}</p>
					</div>
					<div class="col-md-4 ftco-animate">
						<h3 class="h4">Vission</h3>
						<p>{{company.aboutus.vission| safe}}</p>
					</div>
					<div class="col-md-4 ftco-animate">
						<h3 class="h4">Mosaic</h3>
						<p>{{company.aboutus.mosaic| safe}}</p>
					</div>
				</div>
			</div>
		</section>


		<section class="ftco-section ftco-counter img" id="section-counter" style="background-image: url({% static 'web/images/bg_3.jpg' %});" data-stellar-background-ratio="0.5">
    	<div class="container">
    		<div class="row d-md-flex align-items-center justify-content-end">
    			<div class="col-lg-10">
    				<div class="row d-md-flex align-items-center">
		          <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18">
		              <div class="text">
		                <strong class="number" data-number="18">0</strong>
		                <span>Years of Experienced</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18">
		              <div class="text">
		                <strong class="number" data-number="351">0</strong>
		                <span>Happy Clients</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18">
		              <div class="text">
		                <strong class="number" data-number="564">0</strong>
		                <span>Finished Projects</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18">
		              <div class="text">
		                <strong class="number" data-number="300">0</strong>
		                <span>Working Days</span>
		              </div>
		            </div>
		          </div>
	          </div>
          </div>
        </div>
    	</div>
    </section>

    <section class="ftco-section testimony-section bg-light">
      <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-7 heading-section ftco-animate">
          	<span class="subheading subheading-with-line"><small class="pr-2 bg-light">Testimony</small></span>
            <h2 class="mb-4">Our satisfied customer says</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
          </div>
        </div>
        <div class="row ftco-animate">
          <div class="col-md-12">
            <div class="carousel-testimony owl-carousel">
               {% for client in company.clientreview_set.all %}
              <div class="item">
                <div class="testimony-wrap p-4 pb-5">
                  <div class="user-img mb-5" style="background-image: url( /media/{{client.image}} )">
                    <span class="quote d-flex align-items-center justify-content-center">
                      <i class="icon-quote-left"></i>
                    </span>
                  </div>
                  <div class="text">
                    <p class="mb-5 pl-4 line">{{client.review}}</p>
                    <div class="pl-5">
	                    <p class="name">{{client.name}}</p>
	                    <span class="position">{{client.designation}}</span>
                    </div>
                  </div>
                </div>
              </div>
                {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </section>

 {% endblock %}

app/templates/web/blog.html
{% extends 'web/web_base.html' %}
{% load static %}
{% block content %}
    
    <section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'web/images/bg_1.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">Our Blog</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'web_index' company.key company.id %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Blog <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section">
			<div class="container">
				<div class="row">
          <div class="col-lg-8">
          	<div class="row">
				{% for blog in company.blog_set.all %}
				  <div class="col-md-6 ftco-animate">
		            <div class="blog-entry">
		              <a href="{% url 'web_blog_single' company.key company.id %}" class="block-20" style="background-image: url('/media/{{blog.image}}');">
		              </a>
		              <div class="text d-flex py-4">
		                <div class="meta mb-3">
		                  <div><a href="#">{{blog.creation_date|date}}</a></div>
		                  <div><a href="#">Admin</a></div>
		                  <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
		                </div>
		                <div class="desc pl-3">
			                <h3 class="heading"><a href="#">{{blog.title}}</a></h3>
			              </div>
		              </div>
		            </div>
		  </div>
				{% endfor %}
          	</div>
          	<div class="row no-gutters my-5">
		          <div class="col text-center">
		            <div class="block-27">
		              <ul>
		                <li><a href="#">&lt;</a></li>
		                <li class="active"><span>1</span></li>
		                <li><a href="#">2</a></li>
		                <li><a href="#">3</a></li>
		                <li><a href="#">4</a></li>
		                <li><a href="#">5</a></li>
		                <li><a href="#">&gt;</a></li>
		              </ul>
		            </div>
		          </div>
		        </div>
          </div>

          <div class="col-lg-4 sidebar ftco-animate">
            <div class="sidebar-box ftco-animate">
            	<h3>Category</h3>
              <ul class="categories">
                <li><a href="#">Interior Design <span>(6)</span></a></li>
                <li><a href="#">Exterior Design <span>(8)</span></a></li>
                <li><a href="#">Industrial Design <span>(2)</span></a></li>
                <li><a href="#">Landscape Design <span>(2)</span></a></li>
              </ul>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Popular Articles</h3>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url('{% static 'web/images/image_1.jpg' %}');"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> Oct. 04, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Dave Lewis</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url('{% static 'web/images/image_2.jpg' %}');"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> Oct. 04, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Dave Lewis</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url('{% static 'web/images/image_3.jpg' %}');"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> Oct. 04, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Dave Lewis</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Tag Cloud</h3>
              <ul class="tagcloud m-0 p-0">
                <a href="#" class="tag-cloud-link">House</a>
                <a href="#" class="tag-cloud-link">Office</a>
                <a href="#" class="tag-cloud-link">Land</a>
                <a href="#" class="tag-cloud-link">Building</a>
                <a href="#" class="tag-cloud-link">Table</a>
                <a href="#" class="tag-cloud-link">Intrior</a>
                <a href="#" class="tag-cloud-link">Exterior</a>
              </ul>
            </div>

            <div class="sidebar-box ftco-animate">
            	<h3>Archives</h3>
              <ul class="categories">
              	<li><a href="#">December 2018 <span>(30)</span></a></li>
              	<li><a href="#">Novemmber 2018 <span>(20)</span></a></li>
                <li><a href="#">September 2018 <span>(6)</span></a></li>
                <li><a href="#">August 2018 <span>(8)</span></a></li>
              </ul>
            </div>


            <div class="sidebar-box ftco-animate">
              <h3>Paragraph</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div><!-- END COL -->
        </div>
			</div>
		</section>
{%endblock%}

app/templates/web/project.html
{% extends 'web/web_base.html' %}
{% load static %}
{% block content %}
    
    <section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'web/images/bg_1.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">Project</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'web_index'  company.key company.id %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Project <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-start mb-5 pb-2">
          <div class="col-md-4 heading-section ftco-animate">
          	<span class="subheading subheading-with-line"><small class="pr-2 bg-white">Projects</small></span>
            <h2 class="mb-4">Featured Projects</h2>
          </div>
          <div class="col-md-8 pl-md-5 heading-section ftco-animate">
          	<div class="pl-md-4 border-line">
	          	<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
	          	<p class="category mt-5">
	            	<span class="active mr-2"><a href="#">All Work</a></span>
	            	<span class="mr-2"><a href="#">Interior</a></span>
	            	<span class="mr-2"><a href="#">Exterior</a></span>
	            	<span class="mr-2"><a href="#">Landscape</a></span>
	            </p>
          	</div>
          </div>
        </div>
    	</div>
    	<div class="container-wrap">
    		<div class="row no-gutters">
				{% for image in company.interiordesignimage_set.all %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="project">
	    				<img src="/media/{{image.image}}" class="img-fluid" alt="Colorlib Template">
	    				<div class="text">
	    					<span>Interior Design</span>
	    					<h3><a href="{% url 'web_project' company.key company.id %}">Office Interior Design</a></h3>
	    				</div>
	    				<a href="/media/{{image.image}}" class="icon image-popup d-flex justify-content-center align-items-center">
	    					<span class="icon-expand"></span>
	    				</a>
    				</div>
    			</div>
    			{% endfor %}
    		</div>
    		<div class="row no-gutters mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
    	</div>
    </section>
 
{% endblock %}

app/templates/web/services.html
{% extends 'web/web_base.html' %}
{% load static %}
{% block content %}

    
    <section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'web/images/bg_1.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">Services</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'web_index' company.key company.id %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Services <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

		<section class="ftco-services">
			<div class="container">
				<div class="row justify-content-start mb-5 pb-5">
          <div class="col-md-4 heading-section ftco-animate">
            <h2 class="mb-4">Our Work Flow</h2>
          </div>
          <div class="col-md-8 pl-md-5 ftco-animate">
          	<div class="pl-md-4 border-line">
	          	<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in.</p>
          	</div>
          </div>
        </div>
				<div class="row">
          <div class="col-md-4 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services d-block">
              <div class="icon d-flex justify-content-center align-items-center">
            		<span class="flaticon-idea"></span>
              </div>
              <div class="media-body p-2 mt-3">
                <h3 class="heading">Perfectly Design</h3>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
              </div>
            </div>
          </div>
          <div class="col-md-4 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services d-block">
              <div class="icon d-flex justify-content-center align-items-center">
            		<span class="flaticon-compass-symbol"></span>
              </div>
              <div class="media-body p-2 mt-3">
                <h3 class="heading">Carefully Planned</h3>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
              </div>
            </div>
          </div>
          <div class="col-md-4 d-flex align-self-stretch ftco-animate">
            <div class="media block-6 services d-block">
              <div class="icon d-flex justify-content-center align-items-center">
            		<span class="flaticon-layers"></span>
              </div>
              <div class="media-body p-2 mt-3">
                <h3 class="heading">Smartly Execute</h3>
                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row justify-content-start mt-5 py-5">
          <div class="col-md-4 heading-section ftco-animate">
            <h2 class="mb-4">Our Services</h2>
            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic.</p>
          </div>
          <div class="col-md-8 ftco-animate">
          	<div class="row d-flex">
          		 {% for service in company.services_set.all %}
                    <div class="col-md-6 d-flex align-items-stretch">
                        <div class="media block-6 services services-2 d-block bg-light p-4 mb-4">
                            <div class="icon d-flex justify-content-center align-items-center">
                                <span class="flaticon-layers"></span>
                            </div>
                            <div class="media-body p-2 mt-3">
                                <h3 class="heading">{{service.name}}</h3>
                                <p>{{service.details|safe}}</p>
                            </div>
                        </div>
                    </div>
                   {% endfor %}
          	</div>
          </div>
        </div>
			</div>
		</section>

		<section class="ftco-section bg-light">
    	<div class="container">
    		<div class="row justify-content-start mb-5 pb-2">
          <div class="col-md-4 heading-section ftco-animate">
          	<span class="subheading subheading-with-line"><small class="pr-2 bg-light">Projects</small></span>
            <h2 class="mb-4">Done Projects</h2>
          </div>
          <div class="col-md-8 pl-md-5 heading-section ftco-animate">
          	<div class="pl-md-4 border-line">
	          	<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
          	</div>
          </div>
        </div>
    	</div>
    	<div class="container">
    		<div class="row">
                {% for image in company.interiordesignimage_set.all|slice:"0:4" %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="project">
	    				<img src="/media/{{image.image}}" class="img-fluid" alt="Colorlib Template">
	    				<div class="text">
	    					<span>Interior Design</span>
	    					<h3><a href="{% url 'web_project' company.key company.id %}">Office Interior Design</a></h3>
	    				</div>
	    				<a href="/media/{{image.image}}" class="icon image-popup d-flex justify-content-center align-items-center">
	    					<span class="icon-expand"></span>
	    				</a>
    				</div>
    			</div>
    			{% endfor %}
    	</div>
        </div>
    </section>
    
  {% endblock %}

app/templates/web/team.html
 {% extends 'web/web_base.html' %}
{% load static %}
{% block content %}

    <section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'web/images/bg_1.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">Our Architect</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'web_index' company.key company.id %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Team <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section">
			<div class="container">
				<div class="row justify-content-center mb-5 pb-3">
          <div class="col-md-7 heading-section ftco-animate">
          	<span class="subheading subheading-with-line"><small class="pr-2 bg-white">Expert Team</small></span>
            <h2 class="mb-4">Our Architect Team</h2>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
          </div>
        </div>	
				<div class="row">
                    {% for customer in company.customer_set.all %}
					<div class="col-md-6 col-lg-3 ftco-animate">
						<div class="staff">
							<div class="img" style="background-image: url( /media/{{customer.profile_pic}} );"></div>
							<div class="text px-4 pt-4">
								<h3>{{customer.first_name}} {{customer.last_name}}</h3>
								<span class="position mb-2">{{customer.designation}}</span>
								<div class="faded">
									<p>{{customer.descripsion}}</p>
									<ul class="ftco-social d-flex">
		                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
		                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
		                <li class="ftco-animate"><a href="#"><span class="icon-google-plus"></span></a></li>
		                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
		              </ul>
	              </div>
							</div>
						</div>
					</div>
                    {% endfor %}
				</div>
			</div>
		</section>

		<section class="ftco-section bg-light">
    	<div class="container">
    		<div class="row justify-content-start mb-5 pb-2">
          <div class="col-md-4 heading-section ftco-animate">
          	<span class="subheading subheading-with-line"><small class="pr-2 bg-light">Projects</small></span>
            <h2 class="mb-4">Recent Projects</h2>
          </div>
          <div class="col-md-8 pl-md-5 heading-section ftco-animate">
          	<div class="pl-md-4 border-line">
	          	<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
          	</div>
          </div>
        </div>
    	</div>
    	<div class="container">
    		<div class="row">
				{% for image in company.interiordesignimage_set.all|slice:"0:4" %}
    			<div class="col-md-6 col-lg-3 ftco-animate">
    				<div class="project">
	    				<img src="/media/{{image.image}}" class="img-fluid" alt="Colorlib Template">
	    				<div class="text">
	    					<span>Interior Design</span>
	    					<h3><a href="{% url 'web_project' company.key company.id %}">Office Interior Design</a></h3>
	    				</div>
	    				<a href="/media/{{image.image}}" class="icon image-popup d-flex justify-content-center align-items-center">
	    					<span class="icon-expand"></span>
	    				</a>
    				</div>
    			</div>
    			{% endfor %}
    	</div>
		</div>
    </section>
    
 {% endblock %}