CMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_url = "/app"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from autoslug import AutoSlugField

gender_choices = [
    ('M', 'Male'),
    ('F', 'Female')
]

# Create your models here.


class Company(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    description = HTMLField(blank=True, default=u'')
    promo_url = models.URLField(blank=True, null=True)
    address = models.TextField(max_length=500, blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=25, blank=True, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    key = AutoSlugField(populate_from='title', unique_with=['name', 'creation_date'])
    password = models.CharField(max_length=150, blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    company_logo = models.ImageField(default='', blank=True, null=True)

    def __str__(self):
        return self.name


class Customer(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    designation = models.CharField(max_length=50, blank=True, null=True)
    descripsion = models.TextField(max_length=500, blank=True, null=True)
    gender = models.CharField(max_length=10, choices=gender_choices, default='None', null=True, blank=True)
    profile_pic = models.ImageField(default='', blank=True, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)


class AboutUs(models.Model):
    company = models.OneToOneField(Company, on_delete=models.CASCADE)
    title = models.CharField(max_length=250, null=True, blank=True)
    details = HTMLField(blank=True, default=u'')
    mission = HTMLField(blank=True, default=u'')
    vission = HTMLField(blank=True, default=u'')
    mosaic = HTMLField(blank=True, default=u'')
    image = models.ImageField(default='about_us.jpg', blank=True, null=True)


class Services(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    details = HTMLField(blank=True, default=u'')


class Blog(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    descripsion = HTMLField(blank=True, default=u'')
    creation_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='', blank=True, null=True)


class ClientReview(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    designation = models.CharField(max_length=50, blank=True, null=True)
    review = models.TextField(max_length=500)
    image = models.ImageField(default='', blank=True, null=True)


class AnimationView(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    header = models.CharField(max_length=50)
    title = models.CharField(max_length=300)
    descripsion = models.TextField(max_length=500, blank=True, null=True)
    backgroun_image = models.ImageField(default='', blank=True, null=True)


class InteriorDesignImage(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    image = models.ImageField(default='')

app/templates/aboutus_form.html
<!DOCTYPE html> {% extends 'company_base.html' %}
<html lang="en">

<head>
    <meta charset="UTF-8">
</head>

<body class="hold-transition skin-blue sidebar-mini">
    {% block content %}

    <style>
        th {
            font-size: 16px;
            padding: 3px 10px 8px 0px;
        }

        td {
            0px 8px 3px 2px;
        }

        body {
            font-family: "Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

          textarea{
            width: 219px;
            height: 85px;
        }
    </style>

    <center>

        {% if messages %} {% for msg in messages %} {%if msg%}
        <script>
            Swal.fire({
                position: 'top-end',
                type: 'success',
                title: '{{msg.message}}',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
        {%endif%} {% endfor %} {% endif %}

        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title" style="font-size:25px">Add About Us </h3>
            </div>
            <form role="form" method="post" action="{% url 'create_aboutus' %}" enctype="multipart/form-data">
                <div class="box-body">
                    <table>
                        {% csrf_token %} {{form.as_table}}
                    </table>
                </div>
                <div class="box-footer">
                    <input type="submit" class="btn btn-primary" >
                    <button type="reset" class="btn btn-primary">Reset</button>
                </div>
            </form>
        </div>
    </center>
    {% endblock %}
</body>

</html>

app/templates/animationview_form.html
<!DOCTYPE html> {% extends 'company_base.html' %}
<html lang="en">

<head>
    <meta charset="UTF-8">
</head>

<body class="hold-transition skin-blue sidebar-mini">
    {% block content %}
<script>
  $(document).ready(function(){
    $('#id_file').attr("multiple","true");

  })
     function myDelete(id) {

            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {

                    if (id != null) {

                        Swal.fire(
                            'Deleted!',
                            'Your file has been deleted.',
                            'success'
                        )

                        var url = "{% url 'delete_animation' 123 %}";
                        var id_ = id;

                        // // Construct the full URL with "id"
                        document.location.href = url.replace('123', id_);

                    }
                }
            })

        }
 </script>

    <style>
        th {
            font-size: 16px;
            padding: 3px 10px 8px 0px;
        }

        td {
            0px 8px 3px 2px;
        }

        body {
            font-family: "Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

          textarea{
            width: 219px;
            height: 95px;
        }

            img{
            width: 100px;
            height: 100px;
        }
    </style>

    <center>

        {% if messages %} {% for msg in messages %} {%if msg%}
        <script>
            Swal.fire({
                position: 'top-end',
                type: 'success',
                title: '{{msg.message}}',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
        {%endif%} {% endfor %} {% endif %}

        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title" style="font-size:25px">Add Animation View </h3>
            </div>
            <form role="form" method="post" action="{% url 'create_animation' %}" enctype="multipart/form-data">
                <div class="box-body">
                    <table>
                        {% csrf_token %} {{form.as_table}}
                    </table>
                </div>
                <div class="box-footer">
                    <input type="submit" class="btn btn-primary" {% if object.id %}  value="Update" formaction="{% url 'update_animation' object.id %}" {%endif%} >
                    <button type="reset" class="btn btn-primary">Reset</button>
                </div>
            </form>
        </div>
    </center>


       <div class="row">
        <div class="col-xs-12">
          <!-- /.box -->

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Id</th>
                  <th>title</th>
                  <th>header</th>
                  <th>descripsion</th>
                  <th>Company</th>
                  <th>Image</th>
                  <th>Update</th>
                  <th>Delete</th>

                </tr>
                </thead>
                <tbody>
                  {% for animation in animation_list %}
                    <tr>
                        <td>{{animation.id}}</td>
                        <td>{{animation.title}}</td>
                        <td>{{animation.header}}</td>
                        <td>{{animation.descripsion|safe}}</td>
                        <td>{{animation.company}}</td>
                        <td><img src="/media/{{animation.backgroun_image}}"></td>
                         <td>
                            <a href="{% url 'update_animation' animation.id %}">
                                <i class="fa fa-pencil-square-o"></i></a>
                        </td>
                        <td><i class="fa fa-trash-o" onclick="myDelete({{animation.id}})" aria-hidden="true"></i></td>

                    </tr>
                    {%endfor%}
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>


    {% endblock %}
</body>

</html>

app/templates/blog_form.html
<!DOCTYPE html> {% extends 'company_base.html' %}
<html lang="en">

<head>
    <meta charset="UTF-8">
</head>

<body class="hold-transition skin-blue sidebar-mini">
    {% block content %}
<script>
  $(document).ready(function(){
    $('#id_file').attr("multiple","true");

  })
     function myDelete(id) {

            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {

                    if (id != null) {

                        Swal.fire(
                            'Deleted!',
                            'Your file has been deleted.',
                            'success'
                        )

                        var url = "{% url 'delete_blog' 123 %}";
                        var id_ = id;

                        // // Construct the full URL with "id"
                        document.location.href = url.replace('123', id_);

                    }
                }
            })

        }
 </script>

    <style>
        th {
            font-size: 16px;
            padding: 3px 10px 8px 0px;
        }

        td {
            0px 8px 3px 2px;
        }

        body {
            font-family: "Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

          textarea{
            width: 219px;
            height: 95px;
        }

        img{
            width: 50px;
            height: 50px;
        }

    </style>

    <center>

        {% if messages %} {% for msg in messages %} {%if msg%}
        <script>
            Swal.fire({
                position: 'top-end',
                type: 'success',
                title: '{{msg.message}}',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
        {%endif%} {% endfor %} {% endif %}

        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title" style="font-size:25px">Add Blog</h3>
            </div>
            <form role="form" method="post" action="{% url 'create_blog' %}" enctype="multipart/form-data">
                <div class="box-body">
                    <table>
                        {% csrf_token %} {{form.as_table}}
                    </table>
                </div>
                <div class="box-footer">
                    <input type="submit" class="btn btn-primary" {% if object.id %}  value="Update" formaction="{% url 'update_blog' object.id %}" {%endif%}>
                    <button type="reset" class="btn btn-primary">Reset</button>
                </div>
            </form>
        </div>
    </center>


       <div class="row">
        <div class="col-xs-12">
          <!-- /.box -->

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Id</th>
                  <th>Title</th>
                  <th>Descripsion</th>
                  <th>Creation Date</th>
                  <th>Image</th>
                  <th>Update</th>
                  <th>Delete</th>

                </tr>
                </thead>
                <tbody>
                  {% for blog in blog_list %}
                    <tr>
                        <td>{{blog.id}}</td>
                        <td>{{blog.title}}</td>
                        <td>{{blog.descripsion|safe}}</td>
                        <td>{{blog.creation_date}}</td>
                        <td><img src="/media/{{blog.image}}"></td>
                         <td>
                            <a href="{% url 'update_blog' blog.id %}">
                                <i class="fa fa-pencil-square-o"></i></a>
                        </td>
                        <td><i class="fa fa-trash-o" onclick="myDelete({{blog.id}})" aria-hidden="true"></i></td>

                    </tr>
                    {%endfor%}
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>


    {% endblock %}
</body>

</html>

app/templates/clientreview_form.html
<!DOCTYPE html> {% extends 'company_base.html' %}
<html lang="en">

<head>
    <meta charset="UTF-8">
</head>

<body class="hold-transition skin-blue sidebar-mini">
    {% block content %}
<script>
  $(document).ready(function(){
    $('#id_file').attr("multiple","true");

  })
     function myDelete(id) {

            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {

                    if (id != null) {

                        Swal.fire(
                            'Deleted!',
                            'Your file has been deleted.',
                            'success'
                        )

                        var url = "{% url 'delete_client_review' 123 %}";
                        var id_ = id;

                        // // Construct the full URL with "id"
                        document.location.href = url.replace('123', id_);

                    }
                }
            })

        }
 </script>

    <style>
        th {
            font-size: 16px;
            padding: 3px 10px 8px 0px;
        }

        td {
            0px 8px 3px 2px;
        }

        body {
            font-family: "Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

          textarea{
            width: 219px;
            height: 95px;
        }

        img{
            width: 50px;
            height: 50px;
        }

    </style>

    <center>

        {% if messages %} {% for msg in messages %} {%if msg%}
        <script>
            Swal.fire({
                position: 'top-end',
                type: 'success',
                title: '{{msg.message}}',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
        {%endif%} {% endfor %} {% endif %}

        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title" style="font-size:25px">Add Client Reviews</h3>
            </div>
            <form role="form" method="post" action="{% url 'create_client_review' %}" enctype="multipart/form-data">
                <div class="box-body">
                    <table>
                        {% csrf_token %} {{form.as_table}}
                    </table>
                </div>
                <div class="box-footer">
                    <input type="submit" class="btn btn-primary" {% if object.id %}  value="Update" formaction="{% url 'update_client_review' object.id %}" {%endif%} >
                    <button type="reset" class="btn btn-primary">Reset</button>
                </div>
            </form>
        </div>
    </center>


       <div class="row">
        <div class="col-xs-12">
          <!-- /.box -->

          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Data Table With Full Features</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Id</th>
                  <th>Name</th>
                  <th>Designation</th>
                  <th>Review </th>
                  <th>company</th>
                  <th>Image</th>
                  <th>Update</th>
                  <th>Delete</th>

                </tr>
                </thead>
                <tbody>
                  {% for client in client_list %}
                    <tr>
                        <td>{{client.id}}</td>
                        <td>{{client.name}}</td>
                        <td>{{client.designation}}</td>
                        <td>{{client.review|safe}}</td>
                        <td>{{client.company}}</td>
                        <td><img src="/media/{{client.image}}"></td>
                         <td>
                            <a href="{% url 'update_client_review' client.id %}">
                                <i class="fa fa-pencil-square-o"></i></a>
                        </td>
                        <td><i class="fa fa-trash-o" onclick="myDelete({{client.id}})" aria-hidden="true"></i></td>

                    </tr>
                    {%endfor%}
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>


    {% endblock %}
</body>

</html>

app/templates/company_form.html
<!DOCTYPE html> {% extends 'base.html' %}
<html lang="en">

<head>
    <meta charset="UTF-8">
</head>

<body class="hold-transition skin-blue sidebar-mini">
    {% block content %}

    <style>
        th {
            font-size: 16px;
            padding: 3px 10px 8px 0px;
        }

        td {
            0px 8px 3px 2px;
        }

        body {
            font-family: "Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", Helvetica, Arial, sans-serif;
        }

          textarea{
            width: 219px;
            height: 95px;
        }
    </style>

    <center>

        {% if messages %} {% for msg in messages %} {%if msg%}
        <script>
            Swal.fire({
                position: 'top-end',
                type: 'success',
                title: '{{msg.message}}',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
        {%endif%} {% endfor %} {% endif %}

        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title" style="font-size:25px">Create Company Form</h3>
            </div>
            <form role="form" method="post" action="{% url 'add_company' %}" enctype="multipart/form-data">
                <div class="box-body">
                    <table>
                        {% csrf_token %} {{form.as_table}}
                    </table>
                </div>
                <div class="box-footer">
                    <input type="submit" class="btn btn-primary"  {% if object.id %}  value="Update" formaction="{% url 'update_company' object.id %}" {%endif%}>
                    <button type="reset" class="btn btn-primary">Reset</button>
                </div>
            </form>
        </div>
    </center>
    {% endblock %}
</body>

</html>

app/templates/company_list.html
<!DOCTYPE html> {% extends 'base.html' %} {% block content %}


<h2 class="page-header">List of Company</h2>
    <center>
        {%if not company_list %}
        <div class="alert alert-danger" role="alert" style="width: 500px;">
            Sorry! no records found
        </div>
        {%endif%} {% if messages %} {% for msg in messages %} {%if msg%}
        <script>
            Swal.fire({
                position: 'top-end',
                type: 'success',
                title: '{{msg.message}}',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
        {%endif%} {% endfor %} {% endif %}

    </center>

    <script>
        function myDelete(id) {

            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {

                    if (id != null) {

                        Swal.fire(
                            'Deleted!',
                            'Your file has been deleted.',
                            'success'
                        )

                        var url = "{% url 'delete_company' 123 %}";
                        var id_ = id;

                        // // Construct the full URL with "id"
                        document.location.href = url.replace('123', id_);

                    }
                }
            })

        }
    </script>

    <div class="row">
        {% for company in company_list %}
        <div class="col-md-4">
            <!-- Widget: user widget style 1 -->
            <div class="box box-widget widget-user-2">
                <!-- Add the bg color to the header using any of the bg-* classes -->

                    <div class="widget-user-header bg-yellow">

                    <a href="{% url 'update_company' company.id %}">
                        <i class="fa fa-pencil-square-o" style="font-size: 20px; float: right; color: #3c8dbc; margin: -16px 9px;"></i></a>

                    <i class="fa fa-trash-o" aria-hidden="true" onclick="myDelete({{company.id}})" style="color: black;font-size: 19px;float: right; margin: -16px -12px;"></i>
                    <div class="widget-user-image">
                        <img class="img-circle" src="media/{{company.company_logo}}" alt="{{company.title}} Avatar">
                    </div>
                    <!-- /.widget-user-image -->

                    <h3 class="widget-user-username">{{company.title}}</h3>
                    <h5 class="widget-user-desc">{{company.name}}</h5>
                        <a href="{% url 'web_index' company.key company.id %}" style="float: right; margin: -12px; color: black;">Vist Site</a>
                    </div>

                <div class="box-footer no-padding">
                    <ul class="nav nav-stacked">
                        <li><a href="#">Projects <span class="pull-right badge bg-blue">31</span></a></li>
                        <li><a href="#">Tasks <span class="pull-right badge bg-aqua">5</span></a></li>
                        <li><a href="#">Completed Projects <span class="pull-right badge bg-green">12</span></a></li>
                        <li><a href="#">Followers <span class="pull-right badge bg-red">842</span></a></li>

                    </ul>
                </div>
            </div>
            <!-- /.widget-user -->
        </div>

        {% endfor %}

    </div>

{% endblock %}

app/templates/company_login.html
<!DOCTYPE html> {%load static%}
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CDN CMS | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href='{% static "/bower_components/bootstrap/dist/css/bootstrap.min.css" %}'>
    <!-- Font Awesome -->
    <link rel="stylesheet" href='{% static "/bower_components/font-awesome/css/font-awesome.min.css" %}'>
    <!-- Ionicons -->
    <link rel="stylesheet" href='{% static "/bower_components/Ionicons/css/ionicons.min.css" %}'>
    <!-- Theme style -->
    <link rel="stylesheet" href='{% static "/dist/css/AdminLTE.min.css" %}'>
    <!-- iCheck -->
    <link rel="stylesheet" href='{% static "/plugins/iCheck/square/blue.css" %}'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <b>Company Login</b>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Sign in to start your session</p>

            <form action="{% url 'company_login' %}" method="post">
                {% csrf_token %}
                <div class="form-group has-feedback">
                    <input type="text" class="form-control" placeholder="Email" name="user_id">
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" placeholder="Password" name="password">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox"> Remember Me
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <!-- /.social-auth-links -->

            <a href="#">I forgot my password</a>
            <br>
            <!--<a href="register.html" class="text-center">Register a new membership</a>-->

        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->

    <!-- jQuery 3 -->
    <script src='{% static "/bower_components/jquery/dist/jquery.min.js" %}'></script>
    <!-- Bootstrap 3.3.7 -->
    <script src='{% static "/bower_components/bootstrap/dist/js/bootstrap.min.js" %}'></script>
    <!-- iCheck -->
    <script src='{% static "/plugins/iCheck/icheck.min.js" %}'></script>
    <script>
        $(function() {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' /* optional */
            });
        });
    </script>
</body>

</html>

app/templates/customer_form.html
<!DOCTYPE html>


{% extends request.session.company|yesno:"company_base.html,base.html" %}

<html lang="en">

<head>
    <meta charset="UTF-8">
</head>

<body class="hold-transition skin-blue sidebar-mini">
    {% block content %}

    <style>
        th {
            font-size: 16px;
            padding: 3px 10px 8px 0px;
        }

        td {
            0px 8px 3px 2px;
        }

        textarea{
            width: 219px;
            height: 95px;
        }

    </style>

    <script type="text/javascript">
            $(document).ready(function(){

            $("#id_company").val({{request.session.company.0}});
            $("#id_company").attr("disabled","disabled");

            });
</script>
    <center>
        {% if messages %} {% for msg in messages %} {%if msg%}
        <script>
            Swal.fire({
                position: 'top-end',
                type: 'success',
                title: '{{msg.message}}',
                showConfirmButton: false,
                timer: 1500
            })
        </script>
        {%endif%} {% endfor %} {% endif %}

        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title" style="font-size:25px">Create Customer Form</h3>
            </div>
            <form role="form" enctype="multipart/form-data"  method="post" action="{% url 'add_customer' %}">
                <div class="box-body">
                    <table>
                        {% csrf_token %} {{form.as_table}}
                    </table>
                </div>
                <div class="box-footer">
                    <input type="submit"  class="btn btn-primary" {% if object.id %} value="Update" formaction="{% url 'update_customer' object.id %}" {%endif%}>
                    <button type="reset" class="btn btn-primary">Reset</button>
                </div>
            </form>
        </div>
    </center>
    {% endblock %}
</body>

</html>